# Generated by Django 3.2.4 on 2021-09-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0007_feedoverride_speedoverride_spindlespeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedoverride',
            name='feed_override_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='speedoverride',
            name='speed_override_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='spindlespeed',
            name='spindle_speed_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
