# Generated by Django 3.2.4 on 2021-09-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0010_machinedetails_machinestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
