# Generated by Django 3.2.4 on 2021-09-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0011_auto_20210921_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(choices=[('s', 'speedOvr'), ('f', 'feedRateOvr'), ('a', 'actSpeed')], max_length=20)),
                ('actSpeed_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_app.spindlespeed')),
                ('feedRateOvr_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_app.feedoverride')),
                ('speedOvr_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcua_app.speedoverride')),
            ],
        ),
    ]
