# Generated by Django 3.2.4 on 2021-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0012_anomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedoverride',
            name='speed_override_value',
            field=models.FloatField(default=0),
        ),
    ]
