# Generated by Django 3.2.4 on 2021-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcua_app', '0013_alter_speedoverride_speed_override_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentposition',
            name='b_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currentposition',
            name='x_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currentposition',
            name='y_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currentposition',
            name='z_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedoverride',
            name='feed_override_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='b_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='x_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='y_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='z_axis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='spindlespeed',
            name='spindle_speed_value',
            field=models.FloatField(default=0),
        ),
    ]
